<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.Domain\TaskManager.Domain.csproj" />
    <ProjectReference Include="..\TaskManager.Application\TaskManager.Application.csproj" />
  </ItemGroup>

</Project>
